name: Build and test master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - name: Get the UUID
        run: echo "UUID for this run is ${{ steps.generate-uuid.outputs.uuid }}"
